export const boeken = [
  [1, 'Wuthering Heights', 'WutheringHeights.jpg'],
  [2, 'Gullivers Travels', 'GulliversTravels.jpg'],
  [3, 'A Bend In The River', 'ABendInTheRiver.jpg'],
  [4, 'The Picture Of DorianGray', 'ThePictureOfDorianGray.jpg'],
  [5, 'A Christmas Carol', 'AChristmasCarol.jpg'],
  [6, 'Alice In Wonderland', 'AliceInWonderland.jpg'],
  [7, 'The Quie tAmerican', 'TheQuietAmerican.jpg'],
  [8, 'The Stranger', 'TheStranger.jpg'],
  [9, 'Anna Karenina', 'AnnaKarenina.jpg'],
  [10, 'On The Road', 'OnTheRoad.jpg'],
  [11, 'Anne Frank', 'AnneFrank.jpg'],
  [12, 'A Passage To India', 'APassageToIndia.jpg'],
  [13, 'Bird Song', 'BirdSong.jpg'],
  [14, 'Catch 22', 'Catch22.jpg'],
  [15, 'Don Quichote', 'DonQuichote.jpg'],
  [16, 'Frankenstein', 'Frankenstein.jpg'],
  [17, 'Hamlet', 'Hamlet.jpg'],
  [18, 'Harry Potter Series', 'HarryPotterSeries.jpg'],
  [19, 'His Dark Materials', 'HisDarkMaterials.jpg'],
  [20, 'Jane Eyre', 'JaneEyre.jpg'],
  [21, 'Life Of Pi', 'LifeOfPi.jpg'],
  [22, 'The Catcher In The Rye', 'TheCatcherInTheRye.jpg'],
  [23, 'The Color Purple', 'TheColorPurple.jpg'],
  [24, 'Lord Of The Flies', 'LordOfTheFlies.jpg'],
  [25, 'Memoirs Of A Geisha', 'MemoirsOfAGeisha.jpg'],
  [26, 'The Grapes Of Wrath', 'TheGrapesOfWrath.jpg'],
  [27, 'The Great Gatsby', 'TheGreatGatsby.jpg'],
  [28, 'Men Without Women', 'MenWithoutWomen.jpg'],
  [29, 'The Divine Comedy', 'TheDivineComedy.jpg'],
  [30, 'The Lord Of The Rings', 'TheLordOfTheRings.jpg'],
  [31, 'MobyDick', 'MobyDick.jpg'],
  [32, 'Money', 'Money.jpg'],
  [33, 'Adventures Of Huckleberry Finn', 'AdventuresOfHuckleberryFinn.jpg'],
  [34, 'Nineteen Eighty Four', 'NineteenEightyFour.jpg'],
  [35, 'One Flew Over The Cuckoos Nest', 'OneFlewOverTheCuckoosNest.jpg'],
  [36, 'Pride And Prejudice', 'PrideAndPrejudice.jpg'],
  [37, 'Rebecca', 'Rebecca.jpg'],
  [38, 'Robinson Crusoe', 'RobinsonCrusoe.jpg'],
  [39, 'The Bell Jar', 'TheBellJar.jpg'],
  [40, 'The Canterbury Tales', 'TheCanterburyTales.jpg'],
  [41, 'Brave New World', 'BraveNewWorld.jpg'],
  [42, 'The Count Of Monte Cristo', 'TheCountOfMonteCristo.jpg'],
  [43, 'Heart Of Darkness', 'HeartOfDarkness.jpg'],
  [44, 'The Wind In The Willows', 'TheWindInTheWillows.jpg'],
  [45, 'To Kill A Mockingbird', 'ToKillAMockingbird.jpg'],
  [46, 'Ulysses', 'Ulysses.jpg'],
  [47, 'The War Of The Worlds', 'TheWarOfTheWorlds.jpg'],
  [48, 'The Way We Live Now', 'TheWayWeLiveNow.jpg'],
];
